/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.ResultController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Result;

/**
 *
 * @author Heshan
 */
public class AdminResultViewAndDelete extends javax.swing.JFrame {

    /**
     * Creates new form AdminResultViewAndDelete
     */
    public AdminResultViewAndDelete() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        normalSubBtn = new javax.swing.JRadioButton();
        practicalSubBtn = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        bachelorStuBtn = new javax.swing.JRadioButton();
        masterStuBtn = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        subjectIdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Result View And Delete");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(normalSubBtn);
        normalSubBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        normalSubBtn.setText("Normal Subject");

        buttonGroup1.add(practicalSubBtn);
        practicalSubBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        practicalSubBtn.setText("Practical Subject");
        practicalSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practicalSubBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(bachelorStuBtn);
        bachelorStuBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bachelorStuBtn.setText("Bachelor Student");

        buttonGroup2.add(masterStuBtn);
        masterStuBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        masterStuBtn.setText("Master Student");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Subject ID");

        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(practicalSubBtn)
                            .addComponent(normalSubBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masterStuBtn)
                            .addComponent(bachelorStuBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(viewBtn)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(normalSubBtn)
                .addGap(18, 18, 18)
                .addComponent(practicalSubBtn)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bachelorStuBtn)
                .addGap(18, 18, 18)
                .addComponent(masterStuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(subjectIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(viewBtn)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 260, 310);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Result"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(deleteBtn)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(deleteBtn)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(340, 60, 340, 390);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(100, 450, 70, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_Find01_928435.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 10, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_trash_bin_1370026(1).png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 10, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void practicalSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practicalSubBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_practicalSubBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        ResultController resultCon = new ResultController();
        int subId = Integer.parseInt(subjectIdTxt.getText());
        int res = 0;
        if(normalSubBtn.isSelected() && bachelorStuBtn.isSelected()){
            try {
                res = resultCon.deleteBachelorNormal(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(normalSubBtn.isSelected() && masterStuBtn.isSelected()){
            try {
                res = resultCon.deleteMasterNormal(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(practicalSubBtn.isSelected() && bachelorStuBtn.isSelected()){
            try {
                res = resultCon.deleteBachelorPractical(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(practicalSubBtn.isSelected() && masterStuBtn.isSelected()){
            try {
                res = resultCon.deleteMasterPractical(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(res>0){
            JOptionPane.showMessageDialog(this, "Deleted");
            DefaultTableModel dtm = (DefaultTableModel) resultTable.getModel();
            dtm.setRowCount(0);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        ResultController resultCon = new ResultController();
        ArrayList<Result> resultList = new ArrayList<>();
        int subId = Integer.parseInt(subjectIdTxt.getText());
        if(normalSubBtn.isSelected() && bachelorStuBtn.isSelected()){
            try {
                resultList = resultCon.getExamResultsBacholerNormalSub(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(normalSubBtn.isSelected() && masterStuBtn.isSelected()){
            try {
                resultList = resultCon.getExamResultMasterNormalSub(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(practicalSubBtn.isSelected() && bachelorStuBtn.isSelected()){
            try {
                resultList = resultCon.getExamResultBacholerPracticalSub(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(practicalSubBtn.isSelected() && masterStuBtn.isSelected()){
            try {
                resultList = resultCon.getExamResultMasterPracticalSub(subId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        DefaultTableModel dtm = (DefaultTableModel) resultTable.getModel();
        dtm.setRowCount(0);
        for(Result result : resultList){
            Object[] rowData = {result.getStudentId(), result.getFinalResult()};
            dtm.addRow(rowData);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminResultViewAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminResultViewAndDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bachelorStuBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton masterStuBtn;
    private javax.swing.JRadioButton normalSubBtn;
    private javax.swing.JRadioButton practicalSubBtn;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField subjectIdTxt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
