/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Heshan
 */
public class AdminInterface extends javax.swing.JFrame {

    public static int studentType = 0;
    public AdminInterface() {
        initComponents();
        setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        masterStudentReg = new javax.swing.JButton();
        lectureReg = new javax.swing.JButton();
        instructorReg = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bachelorstudentReg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        deleteStu = new javax.swing.JButton();
        deleteLec = new javax.swing.JButton();
        deleteIns = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        updateStu = new javax.swing.JButton();
        updateLec = new javax.swing.JButton();
        updateIns = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addResult = new javax.swing.JButton();
        updateResult = new javax.swing.JButton();
        deleteResult = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addSubject = new javax.swing.JButton();
        updateSubject = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        clickHereBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        studentDetails = new javax.swing.JButton();
        lectureDetails = new javax.swing.JButton();
        instructorDetails = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        masterStudentInforBtn = new javax.swing.JButton();
        bachelorStudentInforBtn = new javax.swing.JButton();
        lectureInfo = new javax.swing.JButton();
        InstructorInfor = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        viewSubjectDetails = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Admin Area");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        masterStudentReg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        masterStudentReg.setText("Master Student Rejistration");
        masterStudentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterStudentRegActionPerformed(evt);
            }
        });

        lectureReg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lectureReg.setText("Lecture Rejistration");
        lectureReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureRegActionPerformed(evt);
            }
        });

        instructorReg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instructorReg.setText("Instructor Rejistration");
        instructorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorRegActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Rejistration");

        bachelorstudentReg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bachelorstudentReg.setText("BachelorStudent Rejistration");
        bachelorstudentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorstudentRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(instructorReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lectureReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masterStudentReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bachelorstudentReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterStudentReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bachelorstudentReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lectureReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructorReg)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 44, 200, 150);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        deleteStu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteStu.setText("Delete Student");
        deleteStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStuActionPerformed(evt);
            }
        });

        deleteLec.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteLec.setText("Delete Lecture");
        deleteLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLecActionPerformed(evt);
            }
        });

        deleteIns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteIns.setText("Delete Instructor");
        deleteIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Delete Users");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteStu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteLec, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteIns, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteStu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteLec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteIns)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 200, 200, 130);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        updateStu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateStu.setText("Update Student");
        updateStu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStuActionPerformed(evt);
            }
        });

        updateLec.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateLec.setText("Update Lecture");
        updateLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLecActionPerformed(evt);
            }
        });

        updateIns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateIns.setText("Update Instructor");
        updateIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Update Users");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateStu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateLec, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateIns, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateStu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateLec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateIns)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 340, 200, 140);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Result Manage");

        addResult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addResult.setText("Add Result");
        addResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResultActionPerformed(evt);
            }
        });

        updateResult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateResult.setText("View Result");
        updateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResultActionPerformed(evt);
            }
        });

        deleteResult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteResult.setText("Delete Result");
        deleteResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(addResult, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(deleteResult, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(updateResult, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addResult)
                    .addComponent(deleteResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(updateResult)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(220, 45, 390, 190);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Subject Manage");

        addSubject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addSubject.setText("Add Subject");
        addSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectActionPerformed(evt);
            }
        });

        updateSubject.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateSubject.setText("Update Subject");
        updateSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSubjectActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Optional Subject ");

        clickHereBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clickHereBtn.setText("Click here");
        clickHereBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickHereBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(addSubject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                .addComponent(updateSubject))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(clickHereBtn)))
                .addGap(41, 41, 41))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubject)
                    .addComponent(updateSubject))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clickHereBtn)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(220, 240, 390, 150);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("User Details");

        studentDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        studentDetails.setText("Student");
        studentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDetailsActionPerformed(evt);
            }
        });

        lectureDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lectureDetails.setText("Lecture");
        lectureDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureDetailsActionPerformed(evt);
            }
        });

        instructorDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instructorDetails.setText("Instructor");
        instructorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(studentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lectureDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(instructorDetails)
                        .addGap(52, 52, 52))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDetails)
                    .addComponent(lectureDetails)
                    .addComponent(instructorDetails))
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(220, 400, 390, 70);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("View Information");

        masterStudentInforBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        masterStudentInforBtn.setText("Master Student");
        masterStudentInforBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterStudentInforBtnActionPerformed(evt);
            }
        });

        bachelorStudentInforBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bachelorStudentInforBtn.setText("Bachelor Student");
        bachelorStudentInforBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorStudentInforBtnActionPerformed(evt);
            }
        });

        lectureInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lectureInfo.setText("Lecture");
        lectureInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureInfoActionPerformed(evt);
            }
        });

        InstructorInfor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InstructorInfor.setText("Instructor");
        InstructorInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorInforActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bachelorStudentInforBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(masterStudentInforBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lectureInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InstructorInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masterStudentInforBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bachelorStudentInforBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lectureInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InstructorInfor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(620, 140, 120, 160);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Subject Details");

        viewSubjectDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewSubjectDetails.setText("View ");
        viewSubjectDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSubjectDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(viewSubjectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(viewSubjectDetails)
                .addContainerGap())
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(620, 320, 120, 70);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(630, 500, 51, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_admin_87402.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(660, 40, 64, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStuActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStudentChoose().setVisible(true);
            }
        });
    }//GEN-LAST:event_deleteStuActionPerformed

    private void deleteLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLecActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectureSearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_deleteLecActionPerformed

    private void deleteInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInsActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorSearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_deleteInsActionPerformed

    private void updateStuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStuActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStudentChoose().setVisible(true);
            }
        });
    }//GEN-LAST:event_updateStuActionPerformed

    private void updateLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLecActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectureSearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_updateLecActionPerformed

    private void updateInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorSearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_updateInsActionPerformed

    private void addSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSubjectNormalOrPratical().setVisible(true);
            }
        });
    }//GEN-LAST:event_addSubjectActionPerformed

    private void updateSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSubjectActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSubjectNormalOrPratical().setVisible(true);
            }
        });
    }//GEN-LAST:event_updateSubjectActionPerformed

    private void studentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDetailsActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStudentChoose().setVisible(true);
            }
        });
    }//GEN-LAST:event_studentDetailsActionPerformed

    private void lectureDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureDetailsActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectureSearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_lectureDetailsActionPerformed

    private void instructorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorDetailsActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorSearch().setVisible(true);
            }
        });
    }//GEN-LAST:event_instructorDetailsActionPerformed

    private void masterStudentInforBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterStudentInforBtnActionPerformed
        studentType = 2;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BachelorAndMasterStudentView().setVisible(true);
            }
        });
    }//GEN-LAST:event_masterStudentInforBtnActionPerformed

    private void bachelorStudentInforBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorStudentInforBtnActionPerformed
        studentType = 1;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BachelorAndMasterStudentView().setVisible(true);
            }
        });
    }//GEN-LAST:event_bachelorStudentInforBtnActionPerformed

    private void lectureInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureInfoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectureView().setVisible(true);
            }
        });
    }//GEN-LAST:event_lectureInfoActionPerformed

    private void viewSubjectDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSubjectDetailsActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSubjectNormalOrPratical().setVisible(true);
            }
        });
    }//GEN-LAST:event_viewSubjectDetailsActionPerformed

    private void InstructorInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorInforActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorView().setVisible(true);
            }
        });
    }//GEN-LAST:event_InstructorInforActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void masterStudentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterStudentRegActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignPageMaster().setVisible(true);
            }
        });
    }//GEN-LAST:event_masterStudentRegActionPerformed

    private void bachelorstudentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorstudentRegActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignPage().setVisible(true);
            }
        });
    }//GEN-LAST:event_bachelorstudentRegActionPerformed

    private void lectureRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureRegActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectureSignUp().setVisible(true);
            }
        });
    }//GEN-LAST:event_lectureRegActionPerformed

    private void instructorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorRegActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorSignPage().setVisible(true);
            }
        });
    }//GEN-LAST:event_instructorRegActionPerformed

    private void clickHereBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickHereBtnActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionalSubject().setVisible(true);
            }
        });
    }//GEN-LAST:event_clickHereBtnActionPerformed

    private void addResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResultActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultEnter().setVisible(true);
            }
        });
    }//GEN-LAST:event_addResultActionPerformed

    private void updateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResultActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminResultViewAndDelete().setVisible(true);
            }
        });
    }//GEN-LAST:event_updateResultActionPerformed

    private void deleteResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResultActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminResultViewAndDelete().setVisible(true);
            }
        });
    }//GEN-LAST:event_deleteResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InstructorInfor;
    private javax.swing.JButton addResult;
    private javax.swing.JButton addSubject;
    private javax.swing.JButton bachelorStudentInforBtn;
    private javax.swing.JButton bachelorstudentReg;
    private javax.swing.JButton clickHereBtn;
    private javax.swing.JButton deleteIns;
    private javax.swing.JButton deleteLec;
    private javax.swing.JButton deleteResult;
    private javax.swing.JButton deleteStu;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton instructorDetails;
    private javax.swing.JButton instructorReg;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton lectureDetails;
    private javax.swing.JButton lectureInfo;
    private javax.swing.JButton lectureReg;
    private javax.swing.JButton masterStudentInforBtn;
    private javax.swing.JButton masterStudentReg;
    private javax.swing.JButton studentDetails;
    private javax.swing.JButton updateIns;
    private javax.swing.JButton updateLec;
    private javax.swing.JButton updateResult;
    private javax.swing.JButton updateStu;
    private javax.swing.JButton updateSubject;
    private javax.swing.JButton viewSubjectDetails;
    // End of variables declaration//GEN-END:variables
}
