/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.BachelorStudentController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.BachelorStudent;

/**
 *
 * @author Heshan
 */
public class BachelorStudentSearch extends javax.swing.JFrame {

    /**
     * Creates new form BachelorStudentSearch
     */
    public BachelorStudentSearch() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameWithIntialsText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        emailTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressNoTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressRdTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addressTownTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Bachelor Student Id    :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 210, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Full Name              :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 120, 20);

        fullNameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(fullNameTxt);
        fullNameTxt.setBounds(180, 70, 490, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Name With Initials :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 120, 20);

        nameWithIntialsText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameWithIntialsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameWithIntialsTextActionPerformed(evt);
            }
        });
        jPanel1.add(nameWithIntialsText);
        nameWithIntialsText.setBounds(180, 110, 490, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Student ID           :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 120, 20);

        studentId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(studentId);
        studentId.setBounds(180, 150, 490, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Email                  :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 190, 120, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Year                   :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 270, 110, 20);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(590, 460, 51, 23);

        emailTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emailTxt);
        emailTxt.setBounds(180, 190, 490, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Password           :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 230, 120, 20);

        yearTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(yearTxt);
        yearTxt.setBounds(180, 270, 60, 30);

        userNameTxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTxt);
        userNameTxt.setBounds(240, 25, 180, 30);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn);
        searchBtn.setBounds(460, 30, 80, 23);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn);
        updateBtn.setBounds(323, 460, 90, 23);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(430, 460, 80, 23);

        passwordTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        jPanel1.add(passwordTxt);
        passwordTxt.setBounds(180, 230, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Address              :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 310, 120, 20);

        addressNoTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(addressNoTxt);
        addressNoTxt.setBounds(180, 310, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText(",");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 330, 10, 15);

        addressRdTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(addressRdTxt);
        addressRdTxt.setBounds(180, 350, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText(",");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 370, 4, 15);

        addressTownTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressTownTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTownTxtActionPerformed(evt);
            }
        });
        jPanel1.add(addressTownTxt);
        addressTownTxt.setBounds(180, 390, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText(".");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 410, 4, 15);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_system-search_118797.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(610, 10, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameWithIntialsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameWithIntialsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameWithIntialsTextActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        int userName = 0;
        
        try{
            userName =  Integer.parseInt(userNameTxt.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invaild value","error",JOptionPane.ERROR_MESSAGE);
        }
        if(userName != 0){
            try{
                BachelorStudent bstu = BachelorStudentController.searchStudent(userName);
                BachelorStudent bstu1 = BachelorStudentController.searchAddress(userName);
                if(bstu.getStudentId()!= 0){
                    fullNameTxt.setText(bstu.getFullName());
                    nameWithIntialsText.setText(bstu.getNameWithInitials());
                    studentId.setText(Integer.toString(bstu.getStudentId()));
                    emailTxt.setText(bstu.getEmail());
                    yearTxt.setText(Integer.toString(bstu.getYear()));
                    addressNoTxt.setText(bstu1.getAddressNo());
                    addressRdTxt.setText(bstu1.getAddressRd());
                    addressTownTxt.setText(bstu1.getAddressCity());
                    passwordTxt.setText(bstu.getPassword());
                }
                else{
                    JOptionPane.showMessageDialog(this, "No such Bechelor Student");
                    fullNameTxt.setText("");
                    nameWithIntialsText.setText("");
                    studentId.setText("");
                    emailTxt.setText("");
                    yearTxt.setText("");
                    passwordTxt.setText("");
                    addressNoTxt.setText("");
                    addressRdTxt.setText("");
                    addressTownTxt.setText("");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BachelorStudentSearch.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(BachelorStudentSearch.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void addressTownTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTownTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTownTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int stuId = Integer.parseInt(userNameTxt.getText());
        String fullName = fullNameTxt.getText();
        String nameWithInitials = nameWithIntialsText.getText();
        String email = emailTxt.getText();
        String password = passwordTxt.getText();
        int year = Integer.parseInt(yearTxt.getText());
        String addressNo = addressNoTxt.getText();
        String addressRd = addressRdTxt.getText();
        String addressCity = addressTownTxt.getText();
        BachelorStudent bstu = new BachelorStudent();
        bstu.setStudentId(stuId);
        bstu.setFullName(fullName);
        bstu.setNameWithInitials(nameWithInitials);
        bstu.setEmail(email);
        bstu.setPassword(password);
        bstu.setYear(year);
        bstu.setAddressNo(addressNo);
        bstu.setAddressRd(addressRd);
        bstu.setAddressCity(addressCity);
        int res = 0;
        int res1 = 0;
        try{
            res = BachelorStudentController.updateBachelorStudent(bstu);
            res1 = BachelorStudentController.updateAddress(bstu);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BachelorStudentSearch.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BachelorStudentSearch.class.getName()).log(Level.SEVERE, null, ex);
        } 
        if(res>0 && res1>0){
            JOptionPane.showMessageDialog(this, "Update Success");
        }else{
            JOptionPane.showMessageDialog(this, "Update Fail");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int stuId = 0;
        stuId = Integer.parseInt(userNameTxt.getText());
        int res =0;
        try{
            res = BachelorStudentController.deleteBachelorStudent(stuId);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Delete Success");
                fullNameTxt.setText("");
                nameWithIntialsText.setText("");
                studentId.setText("");
                emailTxt.setText("");
                yearTxt.setText("");
                passwordTxt.setText("");
                addressNoTxt.setText("");
                addressRdTxt.setText("");
                addressTownTxt.setText("");
                
            }else{
                JOptionPane.showMessageDialog(this, "Delete Fail");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BachelorStudentSearch.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BachelorStudentSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BachelorStudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BachelorStudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BachelorStudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BachelorStudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BachelorStudentSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressNoTxt;
    private javax.swing.JTextField addressRdTxt;
    private javax.swing.JTextField addressTownTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameWithIntialsText;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField studentId;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
