/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.BachelorStudentController;
import Controller.MasterStudentController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.BachelorStudent;
import model.MasterStudent;
import static views.AdminInterface.studentType;

/**
 *
 * @author Heshan
 */
public class BachelorAndMasterStudentView extends javax.swing.JFrame {

    /**
     * Creates new form BachelorAndMasterStudentView
     */
    public BachelorAndMasterStudentView() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();
        comBtn = new javax.swing.JRadioButton();
        engBtn = new javax.swing.JRadioButton();
        busBtn = new javax.swing.JRadioButton();
        viewBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        titleLabel.setText("Bachelor & Master Student");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(230, 10, 280, 40);

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Full Name", "Name With Initials", "Year", "Email"
            }
        ));
        jScrollPane1.setViewportView(detailTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 90, 700, 360);

        courseGroup.add(comBtn);
        comBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comBtn.setText("Computing");
        jPanel1.add(comBtn);
        comBtn.setBounds(30, 50, 87, 23);

        courseGroup.add(engBtn);
        engBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        engBtn.setText("Engineering");
        jPanel1.add(engBtn);
        engBtn.setBounds(130, 50, 93, 23);

        courseGroup.add(busBtn);
        busBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        busBtn.setText("Business");
        jPanel1.add(busBtn);
        busBtn.setBounds(240, 50, 75, 23);

        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewBtn.setText("view");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBtn);
        viewBtn.setBounds(440, 50, 61, 23);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(590, 460, 51, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_Student-3_379413.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 10, 60, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        comBtn.setActionCommand("Computing");
        engBtn.setActionCommand("Engineering");
        busBtn.setActionCommand("Business");
        String com = courseGroup.getSelection().getActionCommand();
        
        if(studentType == 1){
            titleLabel.setText("Bachelor Student");
            ArrayList<BachelorStudent> bStudentList = new ArrayList<>();
            DefaultTableModel dtm = (DefaultTableModel) detailTable.getModel();
            dtm.setRowCount(0);
            if(com.equals("Computing")){
                try {
                    bStudentList = BachelorStudentController.getAllComputingStudent();
                    for(BachelorStudent bStudent : bStudentList){
                        Object[] rowData = {bStudent.getStudentId(), bStudent.getFullName(), bStudent.getNameWithInitials(), bStudent.getYear(), bStudent.getEmail()};
                        dtm.addRow(rowData);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(com.equals("Engineering")){
                try {
                    bStudentList = BachelorStudentController.getAllEngineeringStudent();
                    for(BachelorStudent bStudent : bStudentList){
                        Object[] rowData = {bStudent.getStudentId(), bStudent.getFullName(), bStudent.getNameWithInitials(), bStudent.getYear(), bStudent.getEmail()};
                        dtm.addRow(rowData);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(com.equals("Business")){
                try {
                    bStudentList = BachelorStudentController.getAllBusinessStudent();
                    for(BachelorStudent bStudent : bStudentList){
                        Object[] rowData = {bStudent.getStudentId(), bStudent.getFullName(), bStudent.getNameWithInitials(), bStudent.getYear(), bStudent.getEmail()};
                        dtm.addRow(rowData);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else if(studentType == 2){
            titleLabel.setText("Master Student");
            ArrayList<MasterStudent> mStudentList = new ArrayList<>();
            DefaultTableModel dtm = (DefaultTableModel) detailTable.getModel();
            dtm.setRowCount(0);
            if(com.equals("Computing")){
                try {
                    mStudentList = MasterStudentController.getAllComputingStudent();
                    for(MasterStudent mStudent : mStudentList){
                        Object[] rowData = {mStudent.getStudentId(), mStudent.getFullName(), mStudent.getNameWithInitials(), mStudent.getYear(), mStudent.getEmail()};
                        dtm.addRow(rowData);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(com.equals("Engineering")){
                try {
                    mStudentList = MasterStudentController.getAllEngineeringStudent();
                    for(MasterStudent mStudent : mStudentList){
                        Object[] rowData = {mStudent.getStudentId(), mStudent.getFullName(), mStudent.getNameWithInitials(), mStudent.getYear(), mStudent.getEmail()};
                        dtm.addRow(rowData);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(com.equals("Business")){
                 try {
                    mStudentList = MasterStudentController.getAllBusinessStudent();
                    for(MasterStudent mStudent : mStudentList){
                        Object[] rowData = {mStudent.getStudentId(), mStudent.getFullName(), mStudent.getNameWithInitials(), mStudent.getYear(), mStudent.getEmail()};
                        dtm.addRow(rowData);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BachelorAndMasterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BachelorAndMasterStudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton busBtn;
    private javax.swing.JRadioButton comBtn;
    private javax.swing.ButtonGroup courseGroup;
    private javax.swing.JTable detailTable;
    private javax.swing.JRadioButton engBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
