/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.BachelorStudentController;
import static Controller.BachelorStudentController.addStudentAlResult;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.AlResult;
import model.BachelorStudent;

public class BachelorDetails extends javax.swing.JFrame {

    /**
     * Creates new form BachelorDetails
     */
    public BachelorDetails() {
        initComponents();
        setSize(700,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alYear = new javax.swing.JTextField();
        gEnglishResult = new javax.swing.JTextField();
        alSubject3 = new javax.swing.JTextField();
        alSubject1 = new javax.swing.JTextField();
        alSubject2 = new javax.swing.JTextField();
        alSubjectResult1 = new javax.swing.JTextField();
        alSubjectResult2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        alSubjectResult3 = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        alRank = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        alIndexNo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("More Details (Bachelor Course)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(165, 0, 370, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("GCE Advance Level Result :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Subject");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 140, 47, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Result");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 140, 37, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Rank   :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 300, 60, 20);

        alYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(alYear);
        alYear.setBounds(120, 100, 75, 25);

        gEnglishResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gEnglishResultActionPerformed(evt);
            }
        });
        jPanel1.add(gEnglishResult);
        gEnglishResult.setBounds(290, 260, 25, 25);
        jPanel1.add(alSubject3);
        alSubject3.setBounds(60, 230, 175, 25);

        alSubject1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(alSubject1);
        alSubject1.setBounds(60, 170, 175, 25);
        jPanel1.add(alSubject2);
        alSubject2.setBounds(60, 200, 175, 25);
        jPanel1.add(alSubjectResult1);
        alSubjectResult1.setBounds(290, 170, 25, 25);
        jPanel1.add(alSubjectResult2);
        alSubjectResult2.setBounds(290, 200, 25, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Genaral English");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 260, 100, 25);

        alSubjectResult3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alSubjectResult3ActionPerformed(evt);
            }
        });
        jPanel1.add(alSubjectResult3);
        alSubjectResult3.setBounds(290, 230, 25, 25);

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(490, 460, 55, 23);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(590, 460, 51, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Index No :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 100, 70, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rank   :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 300, 60, 20);

        alRank.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(alRank);
        alRank.setBounds(120, 300, 75, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Year    :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 100, 60, 20);
        jPanel1.add(alIndexNo);
        alIndexNo.setBounds(370, 100, 110, 25);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 680, 290);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_12_2058811.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 370, 130, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gEnglishResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gEnglishResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gEnglishResultActionPerformed

    private void alSubjectResult3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alSubjectResult3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alSubjectResult3ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        int year =0;
        try{
             year  = Integer.parseInt(alYear.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Year :Please enter number value");
        }
        int indexNo=0;
        try{
            indexNo = Integer.parseInt(alIndexNo.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Index No :Please enter number value");
        }
        String subject1 = alSubject1.getText();
        String subject2 = alSubject2.getText();
        String subject3 = alSubject3.getText();
        String subjects = subject1+","+subject2+","+subject3;
        int rank =0;
        try{
            rank = Integer.parseInt(alRank.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Rank :Please enter number value");
        }
        String result1 = alSubjectResult1.getText();
        String result2 = alSubjectResult2.getText();
        String result3 = alSubjectResult3.getText();
        String results = result1+","+result2+","+result3;
        SignPage sp = new SignPage();
        int stId = sp.stuId;
        AlResult aR = new AlResult(stId,year,indexNo,rank,subjects,results);
        int res =0;
        int course = SignPage.courseId;
        try{
           res = BachelorStudentController.addStudentAlResult(aR);
           if(res>0){
               JOptionPane.showMessageDialog(this,"Added Success");
               if(course == 1000){
                   java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new ComputingDegree().setVisible(true);
                        }
                    });
               }
               else if(course == 2000){
                    java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new BusinessDegree().setVisible(true);
                        }
                    });
               }
               else if(course == 3000){
                   java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new EngineeringDegree().setVisible(true);
                    }
                });   
               }
           }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "No driver found");
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BachelorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BachelorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BachelorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BachelorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BachelorDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alIndexNo;
    private javax.swing.JTextField alRank;
    private javax.swing.JTextField alSubject1;
    private javax.swing.JTextField alSubject2;
    private javax.swing.JTextField alSubject3;
    private javax.swing.JTextField alSubjectResult1;
    private javax.swing.JTextField alSubjectResult2;
    private javax.swing.JTextField alSubjectResult3;
    private javax.swing.JTextField alYear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField gEnglishResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
