/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.AdminController;
import Controller.BachelorStudentController;
import Controller.InstructorController;
import Controller.LectureController;
import Controller.MasterStudentController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Heshan
 */
public class LoginPage extends javax.swing.JFrame {
    
    public static int adminId;
    public static String password;
    public static int comboItem;
    public LoginPage() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginKind = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginPassword = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Login Page");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 0, 140, 60);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        loginKind.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginKind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Lecture", "Instructor", "Bechelor Student", "Master Student" }));
        jPanel2.add(loginKind);
        loginKind.setBounds(270, 25, 110, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Login As     :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(160, 20, 90, 30);

        userName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(userName);
        userName.setBounds(270, 65, 110, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Username  :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(160, 60, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password  :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(160, 100, 80, 30);

        loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(loginPassword);
        loginPassword.setBounds(270, 105, 110, 25);

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_lock_511942(2).png"))); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn);
        loginBtn.setBounds(200, 180, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 50, 520, 230);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(450, 410, 70, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_if_lock_511942.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 300, 140, 125);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        comboItem = (int)loginKind.getSelectedIndex();
        adminId = 0;
        try{
            adminId = Integer.parseInt(userName.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Username :Please enter number value");
        }
        password = loginPassword.getText();
        
        if(comboItem == 0){
            try {
                int res1 = AdminController.adminLogin(adminId, password);
                if(res1==0){
                    JOptionPane.showMessageDialog(this, "Login Successfully");
                    
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                        new AdminInterface().setVisible(true);
                        }
                   });
                }
                else{
                    JOptionPane.showMessageDialog(this,"Username or Password wrong","error",JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else if(comboItem == 1){
            try{
                int res2 = LectureController.lectureLogin(adminId, password);
                if(res2 == 0){
                    JOptionPane.showMessageDialog(this, "Login Successfully");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new LectureInterface().setVisible(true);
                        }
                    });
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Username or Password wrong","error",JOptionPane.ERROR_MESSAGE);
                }
            }catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else if(comboItem == 2){
            try{
                int res2 = InstructorController.instructorLogin(adminId, password);
                if(res2 == 0){
                    JOptionPane.showMessageDialog(this, "Login Successfully");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new InstructorInterface().setVisible(true);
                        }
                    });
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Username or Password wrong","error",JOptionPane.ERROR_MESSAGE);
                }
            }catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else if(comboItem == 3){
            try{
                int res5 = BachelorStudentController.bachelorStudentLogin(adminId, password);
                if (res5 == 0){
                   JOptionPane.showMessageDialog(this, "Login Successfully");
                    
                   java.awt.EventQueue.invokeLater(new Runnable() {
                   public void run() {
                        new BachelorStudentInterface().setVisible(true);
                        }
                    });
                  
                }
                else{
                    JOptionPane.showMessageDialog(this,"Username or Password wrong","error",JOptionPane.ERROR_MESSAGE);
                }
            }catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }  
            
        }
        else if(comboItem == 4){
            try{
                int res5 = MasterStudentController.masterStudentLogin(adminId, password);
                if (res5 == 0){
                   JOptionPane.showMessageDialog(this, "Login Successfully");
                    
                   java.awt.EventQueue.invokeLater(new Runnable() {
                      public void run() {
                        new MasterStudentInterface().setVisible(true);
                        }
                     });
                  
                }
                else{
                    JOptionPane.showMessageDialog(this,"Username or Password wrong","error",JOptionPane.ERROR_MESSAGE);
                }
            }catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Driver not found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }  
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JComboBox<String> loginKind;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
