/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.NormalSubjectController;
import Controller.ResultController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Result;
import static views.BachelorStudentInterface.different;

/**
 *
 * @author Heshan
 */
public class StudentResultView extends javax.swing.JFrame {

    /**
     * Creates new form StudentResultView
     */
    public StudentResultView() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gpaViewBtn = new javax.swing.JButton();
        gpaLabel = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Exam Result");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 30);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Result"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(viewBtn)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(viewBtn)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 340, 370);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Current GPA");

        gpaViewBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gpaViewBtn.setText("View");
        gpaViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaViewBtnActionPerformed(evt);
            }
        });

        gpaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gpaLabel.setText("Click view button");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(gpaViewBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(gpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(gpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(gpaViewBtn)
                .addGap(58, 58, 58))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(370, 50, 310, 250);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn);
        exitBtn.setBounds(580, 450, 70, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_calculator_1291736.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(590, 0, 48, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        LoginPage lopage = new LoginPage();
        ResultController resCon = new ResultController();
        ArrayList<Result> reList = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel) resultTable.getModel();
        dtm.setRowCount(0);
        if(different ==1){
            try {
                reList = resCon.getExamResultsBacholerNormal(lopage.adminId);
                reList.addAll(resCon.getExamResultBacholerPractical(lopage.adminId));
                for(Result result : reList){
                    Object[] rowData = {result.getSubjectId(), result.getFinalResult()};
                    dtm.addRow(rowData);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(different == 2){
            try{
                reList = resCon.getExamResultMasterNormal(lopage.adminId);
                reList.addAll(resCon.getExamResultMasterPractical(lopage.adminId));
                for(Result result : reList){
                    Object[] rowData = {result.getSubjectId(), result.getFinalResult()};
                    dtm.addRow(rowData);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void gpaViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaViewBtnActionPerformed
        ArrayList<Result> reList1 = new ArrayList<>();
        ArrayList<Result> reList2 = new ArrayList<>();
        ResultController resCon = new ResultController();
        LoginPage lopage = new LoginPage();
        if(different == 1){
            try {
                reList1 = resCon.getExamResultsBacholerNormal(lopage.adminId);
                reList2 = resCon.getExamResultBacholerPractical(lopage.adminId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(different == 2){
            try{
                reList1 = resCon.getExamResultMasterNormal(lopage.adminId);
                reList2 = resCon.getExamResultMasterPractical(lopage.adminId);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        double total = 0;
        double credit = 0;
        int subjectId = 0;
        int compulsry = 0;
        String resultLetter = "";
        NormalSubjectController nsc = new NormalSubjectController();
        for(Result result : reList1){
            subjectId = result.getSubjectId();
            try {
                compulsry = nsc.checkOptionalOrNot(subjectId);
                resultLetter = result.getFinalResult();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(StudentResultView.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(compulsry == 1){
                total = total + resCon.gpaCalculate(resultLetter)*3;
                credit = credit + 3;
            }
            else if(compulsry == 0){
                total = total + resCon.gpaCalculate(resultLetter)*2;
                credit = credit + 3;
            }
        }
        for(Result result: reList2){
            subjectId = result.getSubjectId();
            resultLetter = result.getFinalResult();
            total = total + resCon.gpaCalculate(resultLetter)*2;
            credit = credit + 2;
        }
        Double gpa = total/credit;
        gpaLabel.setText(Double.toString(gpa));
    }//GEN-LAST:event_gpaViewBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResultView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JButton gpaViewBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
